travis:
  secure:
    BINSTAR_TOKEN: o0fAHjvdfyDhM/wiGrJOGtRALsAwviU/NW6TBYILR/ae/ykPZyZJocMjZitW5v+/LqDxO25iCVakK0PSRGMpLb611jkVZPjoiRXRj9n2HJY5gkdY5mUyQTKNBfHoIHRanELfgzoVU/74Wm4Pk6wWNRgKsPeyRHPE9prjNwQ2SPkM5OBeghW0BlYQsqUeumP6/Cu4g0hn3XZ0TohsNLC2kABnwPNfyjXNbAok9syRDDqoAZXf8uuGYVpKK7iVs68I/BZAXx3TkFF/VfhtPS8rWJWPfWVNv7PItEVFs1PS5rgd6MIk7SuOdrYL2uglwBU8WXMnZk6PUoboaFaSAGFgfXTLEUcaUQOXz9j0w5IyGZQZJceijpdo+yA+RqxE61MaMQbm8RSs9tSLKCe7FPvP+W+fzEFd5xmBntjIOIz/vpM4cJjeuihg5KKZBfJS5eWU2pZMsLX0PsP8I7JDNkpo9AJEcIW3EWVQ94zjuTwz5n4/dLa5bw9ZgHqPsqdeAVSb+5U7FKcYRzyGJKr/boCfcfVgYcTe/fOdSsG8pxDyY4QVFkEiT8ZDCn+vRzK9kSKTOh444QligC5qxt0EE+rqunxe2LEvr7XGCCb8k1uUwqAmXg7cFQxIHMh3mpezKgUP/n9h8dlpiQjsjrWUmQnT/3Y0EhHrigGMVJtBGe0Jr+Q=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
